CREATE TABLE IF NOT EXISTS Sessions (SessionId TEXT, UserEmail TEXT);
CREATE TABLE IF NOT EXISTS Users (Id INTEGER PRIMARY KEY AUTOINCREMENT, Email TEXT UNIQUE, Password TEXT, CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS Tokens (Id INTEGER PRIMARY KEY AUTOINCREMENT, Issuer TEXT, TimeStep INTEGER, EncryptedSecret TEXT, Algorithm TEXT, Digits INTEGER);
